### ISSUE TITLE
Add new design to Select your last period date 

### ISSUE THREAD

**Issue by sarthology** [sarthology/ovuli#50]
Change the current design to this 

![image](https://user-images.githubusercontent.com/3650216/76297550-fec77380-62dd-11ea-9b82-8acb634e7316.png)

Check files in wireframes folder.

**Comment by narender2031** [comment]
@sarthology  Can I take this one?

**Comment by sarthology** [comment]
Sure

**Comment by narender2031** [comment]
<img width="400" alt="Screenshot 2020-03-19 at 12 11 29 AM" src="https://user-images.githubusercontent.com/25151772/76995658-31283f00-6976-11ea-97b4-93d31dcf13b6.png">


There are some bugs on the wix/react-native-calender package. So we need to use another alternative for this.

**Comment by sarthology** [comment]
Update ?

**Comment by narender2031** [comment]
@sarthology 
<img width="373" alt="Screenshot 2020-03-19 at 12 06 53 AM" src="https://user-images.githubusercontent.com/25151772/77055414-d5ea6100-69f6-11ea-8217-6ca6f003a9be.png">

This is needed minor UI changes. 

There are some bugs in the `wix/react-native-calendar`. Like you cannot change the date on click. Now  I am looking for another NPM package for the calendar.

**Comment by sarthology** [comment]
It looks clean

**Comment by narender2031** [comment]
<img width="1440" alt="Screenshot 2020-03-25 at 12 07 21 AM" src="https://user-images.githubusercontent.com/25151772/77465128-30882080-6e2e-11ea-8ab8-df8da942204b.png">

Not able to push my code after pull the master code. 
There is some issues.

**Comment by narender2031** [comment]
<img width="418" alt="Screenshot 2020-03-25 at 1 32 28 AM" src="https://user-images.githubusercontent.com/25151772/77471599-94afe200-6e38-11ea-99a0-a96f660ffc61.png">

<img width="375" alt="Screenshot 2020-03-25 at 12 24 12 AM" src="https://user-images.githubusercontent.com/25151772/77465640-f53a2180-6e2e-11ea-9997-38e548c56708.png">
 there are some bugs with `wix/react-native-calender` so I found `react-native-calendar-picker` for now. It's' not that much flexible to edit the calendar view. I am figuring out the fix for `wix/react-native-calender` for while.
